apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Profile
metadata:
  name: networking.fluxdev.tpk8s.aws.warroyo.com
  namespace: default
spec:
  requiredCapabilities:
  - name: certificates.tanzu.vmware.com
  - name: multicloud-ingress.tanzu.vmware.com
  - name: egress.tanzu.vmware.com
  traits:
  - alias: multicloud-cert-manager.tanzu.vmware.com
    name: multicloud-cert-manager.tanzu.vmware.com
    values:
      inline:
        multicloud-cert-manager.tanzu.vmware.com:
          duration: 87600h
          name: default-issuer
          privateKey:
            algorithm: ECDSA
            size: 384
          renewBefore: 2160h
          selfSigned:
            commonName: ca.company.biz
            secretName: root-secret
  - alias: multicloud-ingress.tanzu.vmware.com
    name: multicloud-ingress.tanzu.vmware.com
    values:
      inline:
        multicloud-ingress.tanzu.vmware.com:
          domain: fluxdev.tpk8s.aws.warroyo.com
          gslb:
            authentication:
              credentialRef: 5944e67113297b5f9778cb0d14e78709
            dns:
              zoneId: ZITNNUBJHM530
          listenerTemplates:
          - namePrefix: https-
            port: 443
            protocol: HTTPS
            tls:
              secretRef: prod-certs
          - namePrefix: http-
            port: 80
            protocol: HTTP
          name: default-gateway
          useClusterIssuer: true
  - alias: egress.tanzu.vmware.com
    name: egress.tanzu.vmware.com
    values:
      inline:
        egress.tanzu.vmware.com:
          open: true