apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  amer-west-project-kubeconfig
  namespace: ucp-token-generator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store
  target:
    name: amer-west-project-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQRENDQkNTZ0F3SUJBZ0lTQTFQQkhpSmZBZU1pcHZVMTdkejRGUHlQTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRFd0hoY05NalF4TURBeE1EWXdPVFF5V2hjTk1qUXhNak13TURZd09UUXhXakFsTVNNd0lRWURWUVFECkV4cGhjR2t1ZEdGdWVuVXVZMnh2ZFdRdWRtMTNZWEpsTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFOZkpLeW1tcmh1dHN3dHRqY3RCUmI1RWtPc0pzL2VXamVBSi9PTVA3aUtkOUIydQpQVGlOWXJFcFJvYkwvRW9qWXRlTjZqMGdlMDZ5RGhQM2VmRktOUmp0bWdJLy9tS0d4MTN3ejJuQWhYMVE3RnlrCnhkM2hqK0taRjBkdVp0SUg3SUk2cm03MmNKR2tBWGEwSS9sMHNwTU5tUmNlWTlBTFRPc1ptVFNhTmxxZjVwekEKbGRxQWhDYWgzK3ZGa05wMWRObGpGaDlhelFkVUFaWlp0b0VMdGhQUnQ2U09yUzlEVk9rZGx5V2pxbVd2aDRUOQp1YWlNZGUzSTJQcllkMUpTUkhpM2xzVjE3cENKUFVTeGJ0bjd3RS9WNmc0QSt6aFQyU2NzZm8zK250TTE3dlNmClM0OEpJUjFzK2JRWmdyMXM5L1N3K0J5OGVIRVpjdGttSWxqZG52OENBd0VBQWFPQ0FsWXdnZ0pTTUE0R0ExVWQKRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV6VG01Tm9ENkVGT0NHTi9EcHh0S0k3VHZYQzh3SHdZRFZSMGpCQmd3CkZvQVV4YzlHcE9yMHc4QjZiSlhFTGJCZWtpOG00N2t3VndZSUt3WUJCUVVIQVFFRVN6QkpNQ0lHQ0NzR0FRVUYKQnpBQmhoWm9kSFJ3T2k4dmNqRXhMbTh1YkdWdVkzSXViM0puTUNNR0NDc0dBUVVGQnpBQ2hoZG9kSFJ3T2k4dgpjakV4TG1rdWJHVnVZM0l1YjNKbkx6QmRCZ05WSFJFRVZqQlVnaHBoY0drdWRHRnVlblV1WTJ4dmRXUXVkbTEzCllYSmxMbU52YllJYWRHMWpMblJoYm5wMUxtTnNiM1ZrTG5adGQyRnlaUzVqYjIyQ0duUnpiUzUwWVc1NmRTNWoKYkc5MVpDNTJiWGRoY21VdVkyOXRNQk1HQTFVZElBUU1NQW93Q0FZR1o0RU1BUUlCTUlJQkJBWUtLd1lCQkFIVwplUUlFQWdTQjlRU0I4Z0R3QUhZQVNMRGphOXFtUnpRUDVXb0MrcDB3Nnh4U0FjdFczU3lCMmJ1L3F6blloSE1BCkFBR1NSdWgweUFBQUJBTUFSekJGQWlFQThGbHdWNFdGWCtOMTdmTE9XcWpkcjdLWG9hTTdMSmQ0aGZpSTNneFgKcUVrQ0lBMlBleE0zWXZRMHBaejBOSEhXMWlYREZSdnVxM3hjUGp1WmYwbHNvb1Y4QUhZQW91TUs1RVh2dmEyYgpmamp0UjJkM1U5ZUNXNFNVMXl0ZUd5ekV1VkNrUitjQUFBR1NSdWgweHdBQUJBTUFSekJGQWlBemtzOUExOGZoCmtLNFFiNDNQdVBZdEk0bTA5aTNlY2NIeTI0SFZKZDJyYWdJaEFNZ0IvTDkvcjEwRUsyVnhveE0xeUtLOUxzNmEKcDlpMEoxSFo3ekVNZUkzYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1FYK1dySEdIc2NNczJUQlluZzJhWgppaVpNK3FDQXQ3TWJBTitYblBFcXI3MGRhbGhzM1FEWlJpeXNJcU8vSkgwUklzTDBmbjh1MktvMy9BdFhiUW9LCmtWSHlLK3dMcTAxbVE3NUtzOWNZa1V6d25ZYWFyNjRQS2xvblRhcytRYUhsdjgwV1RhcTNQcTZUd0lPa0RGTW0KOEJ0K1BoOUxTQW9PRzBqQk5ySE1rMDYwUEpGalZRSTl2S0xlQ3Fka2Jlb2p3Vm92TnZsTmJpdnRUQ0cyRmZyYQpRb2prb3VVNDA5dmZYK081UTJYanFuNVNhQ1A0ek82SzhvM2FjQjhVa24zUkV2Z2ViRnJnWTJCbmlFanlNOGdsClpwU2RCTVMrUG05UHBNdEtTL0Z6Zjc3dzROU2FwL203UmNUODZBRGtEZ0c2UmtlL0hyOENMeThEYW9kVDhidnkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
              server: https://api.tanzu.cloud.vmware.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/3b65ba5e-52a4-4666-ad29-4eefab93127b
            name: sa-tanzu-platform:AMER-West
          contexts:
          - context:
              cluster: sa-tanzu-platform:AMER-West
              user: sa-tanzu-platform-user
            name: sa-tanzu-platform:AMER-West
          current-context: sa-tanzu-platform:AMER-West
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  warroyo-run-eks-kubeconfig
  namespace: ucp-token-generator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store
  target:
    name: warroyo-run-eks-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQRENDQkNTZ0F3SUJBZ0lTQTFQQkhpSmZBZU1pcHZVMTdkejRGUHlQTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRFd0hoY05NalF4TURBeE1EWXdPVFF5V2hjTk1qUXhNak13TURZd09UUXhXakFsTVNNd0lRWURWUVFECkV4cGhjR2t1ZEdGdWVuVXVZMnh2ZFdRdWRtMTNZWEpsTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFOZkpLeW1tcmh1dHN3dHRqY3RCUmI1RWtPc0pzL2VXamVBSi9PTVA3aUtkOUIydQpQVGlOWXJFcFJvYkwvRW9qWXRlTjZqMGdlMDZ5RGhQM2VmRktOUmp0bWdJLy9tS0d4MTN3ejJuQWhYMVE3RnlrCnhkM2hqK0taRjBkdVp0SUg3SUk2cm03MmNKR2tBWGEwSS9sMHNwTU5tUmNlWTlBTFRPc1ptVFNhTmxxZjVwekEKbGRxQWhDYWgzK3ZGa05wMWRObGpGaDlhelFkVUFaWlp0b0VMdGhQUnQ2U09yUzlEVk9rZGx5V2pxbVd2aDRUOQp1YWlNZGUzSTJQcllkMUpTUkhpM2xzVjE3cENKUFVTeGJ0bjd3RS9WNmc0QSt6aFQyU2NzZm8zK250TTE3dlNmClM0OEpJUjFzK2JRWmdyMXM5L1N3K0J5OGVIRVpjdGttSWxqZG52OENBd0VBQWFPQ0FsWXdnZ0pTTUE0R0ExVWQKRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV6VG01Tm9ENkVGT0NHTi9EcHh0S0k3VHZYQzh3SHdZRFZSMGpCQmd3CkZvQVV4YzlHcE9yMHc4QjZiSlhFTGJCZWtpOG00N2t3VndZSUt3WUJCUVVIQVFFRVN6QkpNQ0lHQ0NzR0FRVUYKQnpBQmhoWm9kSFJ3T2k4dmNqRXhMbTh1YkdWdVkzSXViM0puTUNNR0NDc0dBUVVGQnpBQ2hoZG9kSFJ3T2k4dgpjakV4TG1rdWJHVnVZM0l1YjNKbkx6QmRCZ05WSFJFRVZqQlVnaHBoY0drdWRHRnVlblV1WTJ4dmRXUXVkbTEzCllYSmxMbU52YllJYWRHMWpMblJoYm5wMUxtTnNiM1ZrTG5adGQyRnlaUzVqYjIyQ0duUnpiUzUwWVc1NmRTNWoKYkc5MVpDNTJiWGRoY21VdVkyOXRNQk1HQTFVZElBUU1NQW93Q0FZR1o0RU1BUUlCTUlJQkJBWUtLd1lCQkFIVwplUUlFQWdTQjlRU0I4Z0R3QUhZQVNMRGphOXFtUnpRUDVXb0MrcDB3Nnh4U0FjdFczU3lCMmJ1L3F6blloSE1BCkFBR1NSdWgweUFBQUJBTUFSekJGQWlFQThGbHdWNFdGWCtOMTdmTE9XcWpkcjdLWG9hTTdMSmQ0aGZpSTNneFgKcUVrQ0lBMlBleE0zWXZRMHBaejBOSEhXMWlYREZSdnVxM3hjUGp1WmYwbHNvb1Y4QUhZQW91TUs1RVh2dmEyYgpmamp0UjJkM1U5ZUNXNFNVMXl0ZUd5ekV1VkNrUitjQUFBR1NSdWgweHdBQUJBTUFSekJGQWlBemtzOUExOGZoCmtLNFFiNDNQdVBZdEk0bTA5aTNlY2NIeTI0SFZKZDJyYWdJaEFNZ0IvTDkvcjEwRUsyVnhveE0xeUtLOUxzNmEKcDlpMEoxSFo3ekVNZUkzYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1FYK1dySEdIc2NNczJUQlluZzJhWgppaVpNK3FDQXQ3TWJBTitYblBFcXI3MGRhbGhzM1FEWlJpeXNJcU8vSkgwUklzTDBmbjh1MktvMy9BdFhiUW9LCmtWSHlLK3dMcTAxbVE3NUtzOWNZa1V6d25ZYWFyNjRQS2xvblRhcytRYUhsdjgwV1RhcTNQcTZUd0lPa0RGTW0KOEJ0K1BoOUxTQW9PRzBqQk5ySE1rMDYwUEpGalZRSTl2S0xlQ3Fka2Jlb2p3Vm92TnZsTmJpdnRUQ0cyRmZyYQpRb2prb3VVNDA5dmZYK081UTJYanFuNVNhQ1A0ek82SzhvM2FjQjhVa24zUkV2Z2ViRnJnWTJCbmlFanlNOGdsClpwU2RCTVMrUG05UHBNdEtTL0Z6Zjc3dzROU2FwL203UmNUODZBRGtEZ0c2UmtlL0hyOENMeThEYW9kVDhidnkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
              server: https://api.tanzu.cloud.vmware.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/3b65ba5e-52a4-4666-ad29-4eefab93127b/clustergroup/warroyo-run-eks
            name: sa-tanzu-platform:AMER-West:warroyo-run-eks
          contexts:
          - context:
              cluster: sa-tanzu-platform:AMER-West:warroyo-run-eks
              user: sa-tanzu-platform-user
            name: sa-tanzu-platform:AMER-West:warroyo-run-eks
          current-context: sa-tanzu-platform:AMER-West:warroyo-run-eks
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  flux-dev-kubeconfig
  namespace: ucp-token-generator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store
  target:
    name: flux-dev-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQRENDQkNTZ0F3SUJBZ0lTQTFQQkhpSmZBZU1pcHZVMTdkejRGUHlQTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRFd0hoY05NalF4TURBeE1EWXdPVFF5V2hjTk1qUXhNak13TURZd09UUXhXakFsTVNNd0lRWURWUVFECkV4cGhjR2t1ZEdGdWVuVXVZMnh2ZFdRdWRtMTNZWEpsTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFOZkpLeW1tcmh1dHN3dHRqY3RCUmI1RWtPc0pzL2VXamVBSi9PTVA3aUtkOUIydQpQVGlOWXJFcFJvYkwvRW9qWXRlTjZqMGdlMDZ5RGhQM2VmRktOUmp0bWdJLy9tS0d4MTN3ejJuQWhYMVE3RnlrCnhkM2hqK0taRjBkdVp0SUg3SUk2cm03MmNKR2tBWGEwSS9sMHNwTU5tUmNlWTlBTFRPc1ptVFNhTmxxZjVwekEKbGRxQWhDYWgzK3ZGa05wMWRObGpGaDlhelFkVUFaWlp0b0VMdGhQUnQ2U09yUzlEVk9rZGx5V2pxbVd2aDRUOQp1YWlNZGUzSTJQcllkMUpTUkhpM2xzVjE3cENKUFVTeGJ0bjd3RS9WNmc0QSt6aFQyU2NzZm8zK250TTE3dlNmClM0OEpJUjFzK2JRWmdyMXM5L1N3K0J5OGVIRVpjdGttSWxqZG52OENBd0VBQWFPQ0FsWXdnZ0pTTUE0R0ExVWQKRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV6VG01Tm9ENkVGT0NHTi9EcHh0S0k3VHZYQzh3SHdZRFZSMGpCQmd3CkZvQVV4YzlHcE9yMHc4QjZiSlhFTGJCZWtpOG00N2t3VndZSUt3WUJCUVVIQVFFRVN6QkpNQ0lHQ0NzR0FRVUYKQnpBQmhoWm9kSFJ3T2k4dmNqRXhMbTh1YkdWdVkzSXViM0puTUNNR0NDc0dBUVVGQnpBQ2hoZG9kSFJ3T2k4dgpjakV4TG1rdWJHVnVZM0l1YjNKbkx6QmRCZ05WSFJFRVZqQlVnaHBoY0drdWRHRnVlblV1WTJ4dmRXUXVkbTEzCllYSmxMbU52YllJYWRHMWpMblJoYm5wMUxtTnNiM1ZrTG5adGQyRnlaUzVqYjIyQ0duUnpiUzUwWVc1NmRTNWoKYkc5MVpDNTJiWGRoY21VdVkyOXRNQk1HQTFVZElBUU1NQW93Q0FZR1o0RU1BUUlCTUlJQkJBWUtLd1lCQkFIVwplUUlFQWdTQjlRU0I4Z0R3QUhZQVNMRGphOXFtUnpRUDVXb0MrcDB3Nnh4U0FjdFczU3lCMmJ1L3F6blloSE1BCkFBR1NSdWgweUFBQUJBTUFSekJGQWlFQThGbHdWNFdGWCtOMTdmTE9XcWpkcjdLWG9hTTdMSmQ0aGZpSTNneFgKcUVrQ0lBMlBleE0zWXZRMHBaejBOSEhXMWlYREZSdnVxM3hjUGp1WmYwbHNvb1Y4QUhZQW91TUs1RVh2dmEyYgpmamp0UjJkM1U5ZUNXNFNVMXl0ZUd5ekV1VkNrUitjQUFBR1NSdWgweHdBQUJBTUFSekJGQWlBemtzOUExOGZoCmtLNFFiNDNQdVBZdEk0bTA5aTNlY2NIeTI0SFZKZDJyYWdJaEFNZ0IvTDkvcjEwRUsyVnhveE0xeUtLOUxzNmEKcDlpMEoxSFo3ekVNZUkzYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1FYK1dySEdIc2NNczJUQlluZzJhWgppaVpNK3FDQXQ3TWJBTitYblBFcXI3MGRhbGhzM1FEWlJpeXNJcU8vSkgwUklzTDBmbjh1MktvMy9BdFhiUW9LCmtWSHlLK3dMcTAxbVE3NUtzOWNZa1V6d25ZYWFyNjRQS2xvblRhcytRYUhsdjgwV1RhcTNQcTZUd0lPa0RGTW0KOEJ0K1BoOUxTQW9PRzBqQk5ySE1rMDYwUEpGalZRSTl2S0xlQ3Fka2Jlb2p3Vm92TnZsTmJpdnRUQ0cyRmZyYQpRb2prb3VVNDA5dmZYK081UTJYanFuNVNhQ1A0ek82SzhvM2FjQjhVa24zUkV2Z2ViRnJnWTJCbmlFanlNOGdsClpwU2RCTVMrUG05UHBNdEtTL0Z6Zjc3dzROU2FwL203UmNUODZBRGtEZ0c2UmtlL0hyOENMeThEYW9kVDhidnkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
              server: https://api.tanzu.cloud.vmware.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/3b65ba5e-52a4-4666-ad29-4eefab93127b/space/flux-dev
            name: sa-tanzu-platform:AMER-West:flux-dev
          contexts:
          - context:
              cluster: sa-tanzu-platform:AMER-West:flux-dev
              user: sa-tanzu-platform-user
            name: sa-tanzu-platform:AMER-West:flux-dev
          current-context: sa-tanzu-platform:AMER-West:flux-dev
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  flux-int-kubeconfig
  namespace: ucp-token-generator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store
  target:
    name: flux-int-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQRENDQkNTZ0F3SUJBZ0lTQTFQQkhpSmZBZU1pcHZVMTdkejRGUHlQTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRFd0hoY05NalF4TURBeE1EWXdPVFF5V2hjTk1qUXhNak13TURZd09UUXhXakFsTVNNd0lRWURWUVFECkV4cGhjR2t1ZEdGdWVuVXVZMnh2ZFdRdWRtMTNZWEpsTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFOZkpLeW1tcmh1dHN3dHRqY3RCUmI1RWtPc0pzL2VXamVBSi9PTVA3aUtkOUIydQpQVGlOWXJFcFJvYkwvRW9qWXRlTjZqMGdlMDZ5RGhQM2VmRktOUmp0bWdJLy9tS0d4MTN3ejJuQWhYMVE3RnlrCnhkM2hqK0taRjBkdVp0SUg3SUk2cm03MmNKR2tBWGEwSS9sMHNwTU5tUmNlWTlBTFRPc1ptVFNhTmxxZjVwekEKbGRxQWhDYWgzK3ZGa05wMWRObGpGaDlhelFkVUFaWlp0b0VMdGhQUnQ2U09yUzlEVk9rZGx5V2pxbVd2aDRUOQp1YWlNZGUzSTJQcllkMUpTUkhpM2xzVjE3cENKUFVTeGJ0bjd3RS9WNmc0QSt6aFQyU2NzZm8zK250TTE3dlNmClM0OEpJUjFzK2JRWmdyMXM5L1N3K0J5OGVIRVpjdGttSWxqZG52OENBd0VBQWFPQ0FsWXdnZ0pTTUE0R0ExVWQKRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVApBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVV6VG01Tm9ENkVGT0NHTi9EcHh0S0k3VHZYQzh3SHdZRFZSMGpCQmd3CkZvQVV4YzlHcE9yMHc4QjZiSlhFTGJCZWtpOG00N2t3VndZSUt3WUJCUVVIQVFFRVN6QkpNQ0lHQ0NzR0FRVUYKQnpBQmhoWm9kSFJ3T2k4dmNqRXhMbTh1YkdWdVkzSXViM0puTUNNR0NDc0dBUVVGQnpBQ2hoZG9kSFJ3T2k4dgpjakV4TG1rdWJHVnVZM0l1YjNKbkx6QmRCZ05WSFJFRVZqQlVnaHBoY0drdWRHRnVlblV1WTJ4dmRXUXVkbTEzCllYSmxMbU52YllJYWRHMWpMblJoYm5wMUxtTnNiM1ZrTG5adGQyRnlaUzVqYjIyQ0duUnpiUzUwWVc1NmRTNWoKYkc5MVpDNTJiWGRoY21VdVkyOXRNQk1HQTFVZElBUU1NQW93Q0FZR1o0RU1BUUlCTUlJQkJBWUtLd1lCQkFIVwplUUlFQWdTQjlRU0I4Z0R3QUhZQVNMRGphOXFtUnpRUDVXb0MrcDB3Nnh4U0FjdFczU3lCMmJ1L3F6blloSE1BCkFBR1NSdWgweUFBQUJBTUFSekJGQWlFQThGbHdWNFdGWCtOMTdmTE9XcWpkcjdLWG9hTTdMSmQ0aGZpSTNneFgKcUVrQ0lBMlBleE0zWXZRMHBaejBOSEhXMWlYREZSdnVxM3hjUGp1WmYwbHNvb1Y4QUhZQW91TUs1RVh2dmEyYgpmamp0UjJkM1U5ZUNXNFNVMXl0ZUd5ekV1VkNrUitjQUFBR1NSdWgweHdBQUJBTUFSekJGQWlBemtzOUExOGZoCmtLNFFiNDNQdVBZdEk0bTA5aTNlY2NIeTI0SFZKZDJyYWdJaEFNZ0IvTDkvcjEwRUsyVnhveE0xeUtLOUxzNmEKcDlpMEoxSFo3ekVNZUkzYk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1FYK1dySEdIc2NNczJUQlluZzJhWgppaVpNK3FDQXQ3TWJBTitYblBFcXI3MGRhbGhzM1FEWlJpeXNJcU8vSkgwUklzTDBmbjh1MktvMy9BdFhiUW9LCmtWSHlLK3dMcTAxbVE3NUtzOWNZa1V6d25ZYWFyNjRQS2xvblRhcytRYUhsdjgwV1RhcTNQcTZUd0lPa0RGTW0KOEJ0K1BoOUxTQW9PRzBqQk5ySE1rMDYwUEpGalZRSTl2S0xlQ3Fka2Jlb2p3Vm92TnZsTmJpdnRUQ0cyRmZyYQpRb2prb3VVNDA5dmZYK081UTJYanFuNVNhQ1A0ek82SzhvM2FjQjhVa24zUkV2Z2ViRnJnWTJCbmlFanlNOGdsClpwU2RCTVMrUG05UHBNdEtTL0Z6Zjc3dzROU2FwL203UmNUODZBRGtEZ0c2UmtlL0hyOENMeThEYW9kVDhidnkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
              server: https://api.tanzu.cloud.vmware.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/3b65ba5e-52a4-4666-ad29-4eefab93127b/space/flux-int
            name: sa-tanzu-platform:AMER-West:flux-int
          contexts:
          - context:
              cluster: sa-tanzu-platform:AMER-West:flux-int
              user: sa-tanzu-platform-user
            name: sa-tanzu-platform:AMER-West:flux-int
          current-context: sa-tanzu-platform:AMER-West:flux-int
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token