apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music01
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music01
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2024-10-10T14:32:35Z"
    gitCommit: 8bdeee3c1ec317be1133e0d0e0d9c2f23134c521-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageImage: ghcr.io/warroyo/spring-music01@sha256:87bb538a59eeaa5082acb908f908ff0b0f97f2dff50f29113c965abedd8829cc
    packageRefName: spring-music01.apps.local
    packageVersion: 20241010.1432.35694
    summary: git:8bdeee3 @ 2024-10-10T14:32:35Z
    version: 20241010.1432.35694
  health:
    maxUnavailableReplicas: 10%
  image: ghcr.io/warroyo/spring-music01:20241010.1432.35694@sha256:95fcc45cbd21773901a385bef062bb236b521a6cd9ab27b4257eda2dc01d0068
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music01
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music01
  - for: kubernetes.service-target
    kind: Service
    name: spring-music01
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music01-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music01-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music01-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music01
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music01.apps.local.20241010.1432.35694
  - for: kubernetes.delete
    kind: Secret
    name: spring-music01-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music01-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music01-values
  resources:
    cpu: 300m
    memory: 1Gi
